added possibility to remove messages (by User)
hopefulMechanic/trip-advisor pull request #35
Opened 2019-05-13 19:30 UTC by hopefulMechanic

2019-05-13 19:42 UTC, kleczeks requested changes

2019-05-13 19:42 UTC, kamilkleczek commented on backend/src/main/java/studies/project/tripadvisor/controller/NotificationController.java
> +    @DeleteMapping("deleteMessages/{userId}")
Nie stosuje sie takich nazw. Samo 'messages' wystarczy i metoda DELETE na tym resource

2019-05-13 19:59 UTC, kamilkleczek commented on backend/src/main/java/studies/project/tripadvisor/controller/NotificationController.java
> +    @DeleteMapping("deleteMessages/{userId}")
Nie zauwazylem jeszce ze jest tam userId. Wtedy wedlug mnie caly endpoint powinien wygladac: user/{userId}/messages i metoda DELETE

2019-05-14 06:29 UTC, Axori submitted a review, later dismissed

2019-05-14 19:30 UTC, hopefulMechanic commented on backend/src/main/java/studies/project/tripadvisor/controller/NotificationController.java
> +    @DeleteMapping("deleteMessages/{userId}")
dzięki
zrobione :)

2019-05-14 19:31 UTC, merged